### ISSUE TITLE
Error submitting subscription form

### ISSUE THREAD

**Issue by Evgeniy-Nestraliay** [stcr/subscribe-to-comments-reloaded#596] opened 2020-06-29 08:46 UTC
Previously, the plugin worked correctly, but after the latest updates, the post subscription form has stopped working and shows the error message "server error, contact the administrator", why did this problem arise and how to solve it?

**Comment by BobaWebDev** [comment] 2020-06-29 08:53
Hi @Evgeniy-Nestraliay

Does it happen when you submit the form or does it show up when you just visit a post as well?

**Comment by Evgeniy-Nestraliay** [comment] 2020-06-29 08:59
@BobaWebDev 
Thanks for the quick response, this occurs after submitting the form
https://www.screencast.com/t/dQ1w022PT5

**Comment by BobaWebDev** [comment] 2020-06-29 09:04
@Evgeniy-Nestraliay 

You're welcome.

May I have the URL to the website, will try it out, might give me some clue as to what's happening.

**Comment by Evgeniy-Nestraliay** [comment] 2020-06-29 11:31
yeah, click there to display subscribe form https://www.screencast.com/t/vggJGmCMDFgg
site url: https://otzyvov.net/

**Comment by Evgeniy-Nestraliay** [comment] 2020-06-29 12:35
Ajax request return 404 status code because subscribe url not working now(
Request URL example: https://otzyvov.net/comment-subscriptions.html?srp=98480&srk=b514143b95ca01c46c93a361ed68263d&sra=s

**Comment by BobaWebDev** [comment] 2020-06-29 13:01
@Evgeniy-Nestraliay 

Which version were you running before the update today? There wasn't anything in the latest update compared to the one before it that could cause the 404 on comment subscription.

**Comment by Evgeniy-Nestraliay** [comment] 2020-06-29 13:07
@BobaWebDev 

Honestly, I don’t know what the previous version was, I got to the project recently.
I think that the problem is in the link that I sent you above. Tell me, is there any documentation on building a subscription link?

**Comment by BobaWebDev** [comment] 2020-06-29 13:09
@Evgeniy-Nestraliay 

Oh, I thought it was caused by the latest update, 200629, because you submitted the support request shortly after the update was released.

It's an issue with using a "virtual page" instead of a real page, which can be resolved with:

1. Go to WP Admin > StCR > Management Page
2. Set "Virtual management page" to "No" and save changes
3. Go to WP admin > Pages > Add New and create a page called "Comment subscriptions", the permalink should be comment-subscriptions
4. As the content of that page just add [stcr_management_page]

We'll be getting rid of the "virtual page" approach soon and go with the real page approach (like the one mentioned above, but it'll be automatic).

**Comment by Evgeniy-Nestraliay** [comment] 2020-06-29 13:40
@BobaWebDev 
Thank you very much, your solution works for me.

**Comment by BobaWebDev** [comment] 2020-06-29 13:56
@Evgeniy-Nestraliay 

You're welcome, happy to hear it's sorted out.

**Closed by BobaWebDev** 2020-06-29 13:56 UTC
