### ISSUE TITLE
Email address is not valid

### ISSUE THREAD

**Issue by Loukky** [stcr/subscribe-to-comments-reloaded#676] opened 2021-11-30 21:09 UTC
The latest version,when i test request sub i found this issue,Maybe it is a bug?
Some mail address showed its not valid.
like `someone@students.solano.edu`

**Comment by BobaWebDev** [comment] 2021-12-02 09:38
Since this is a duplicate of the support request on the WordPress.org forum, we'll continue the conversation over there and I'll close this one. 

https://wordpress.org/support/topic/email-address-is-not-valid/

**Closed by BobaWebDev** 2021-12-02 09:38 UTC
