### ISSUE TITLE
Bug Report: Notifications of new comments come with html tags

### ISSUE THREAD

**Issue by igorchernomoretz** [stcr/subscribe-to-comments-reloaded#192] opened 2016-02-04 19:19 UTC
Notifications of new comments come with html tags. How to fix it?

**Comment by Reedyseth** [comment] 2016-02-04 19:21
@igorchernomoretz Please set `Enable HTML emails` to **Yes** and `HTMLify links in emails` to **No**

![image](https://cloud.githubusercontent.com/assets/1228711/12826751/cd7badb8-cb39-11e5-9ad0-a2fbb273a89c.png)

**Comment by igorchernomoretz** [comment] 2016-02-04 19:23
Thanks. I will try

**Comment by Monter** [comment] 2016-02-12 09:33
This unfortunately does not help. I always had a set of e-mails and text off htmlify option, everything worked properly. In the last version of the plug inserts for notifications double HREF tags.

**Comment by Monter** [comment] 2016-02-13 23:51
UPDATE: after returning to the old version, I found the cause of the double HREF tags in notifications:

![messages_after_back](https://cloud.githubusercontent.com/assets/9859492/13030738/24270f18-d2b5-11e5-9ba6-60b11949a24b.png)


Is it possible that she did it to install the new version?

**Comment by Reedyseth** [comment] 2016-02-16 16:32
> I tried to find the cause, but I could not. Return to the previous version solved the problem.

@Monter The root cause is this routine: https://github.com/stcr/subscribe-to-comments-reloaded/blob/master/subscribe-to-comments-reloaded/utils/stcr_upgrade.php#L446

It appears to be buggy, but it tries to replace simple StCR tags and add a link, this is a bug and I will open a new ticket:
https://github.com/stcr/subscribe-to-comments-reloaded/issues/198

**Comment by Reedyseth** [comment] 2016-08-18 18:18
Fixed on this commit https://github.com/stcr/subscribe-to-comments-reloaded/commit/56e914fbcb3753448bde064b43810f5e7ba4ec26

**Closed by Reedyseth** 2016-08-18 18:18 UTC
